# Generated by Django 5.0.2 on 2024-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.IntegerField(),
        ),
    ]
